apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: kafka-topic-trans-1
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    max.message.bytes: 128000
