apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: kafka-topic-compacted
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact
    min.compaction.lag.ms: 100
    # max.compaction.lag.ms: 10000 - available in newest version of Kafka
    min.cleanable.dirty.ratio: 1
