apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: pgs-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.2.1
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    config:
      # auto.create.topics.enable: false
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  zookeeper:
    replicas: 1
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}

