apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: kafka-topic-1
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
